title: "[Script request] "
labels: ["enhancement"]
body:
- type: input
  attributes:
    label: Application Name
    description: Enter the application name.
    placeholder: "e.g., Home Assistant"
  validations:
    required: true
- type: input
  attributes:
    label: Website
    description: Official website or github page.
    placeholder: "e.g., https://www.home-assistant.io/"
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Explain what the application does and why it should be added to Proxmox VE Helper-Scripts.
    placeholder: "e.g., Home Assistant is a popular open-source platform that brings all your smart home devices together in one place. Adding it to Proxmox VE Helper-Scripts would make setup and management on Proxmox easy, letting users quickly get a powerful, self-hosted smart home system up and running."
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Due Diligence
    options:
      - label: "I have searched existing [scripts](https://community-scripts.github.io/Proxmox/scripts) and found no duplicates."
        required: true
      - label: "I have searched existing [discussions](https://github.com/community-scripts/ProxmoxVE/discussions?discussions_q=) and found no duplicate requests."
        required: true
- type: markdown
  attributes:
    value: "Thanks for submitting your request! The team will review it and reach out if we need more information."
