name: "✨ Feature Request"
description: "Suggest a new feature or enhancement."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # ✨ **Feature Request**
        Have an idea for a new feature? Share your thoughts below!

  - type: input
    id: feature_summary
    attributes:
      label: "🌟 Briefly describe the feature"
      placeholder: "e.g., Add support for XYZ"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: "📝 Detailed description"
      placeholder: "Explain the feature in detail"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "💡 Why is this useful?"
      placeholder: "Describe the benefit of this feature"
    validations:
      required: true
