name: "🛠️ Task / General Request"
description: "Request a general task, improvement, or refactor."
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        # 🛠️ **Task / General Request**
        Request a task that isn't a bug or feature request.

  - type: input
    id: task_summary
    attributes:
      label: "📌 Task summary"
      placeholder: "e.g., Refactor XYZ"
    validations:
      required: true

  - type: textarea
    id: task_details
    attributes:
      label: "📋 Task details"
      placeholder: "Explain what needs to be done"
    validations:
      required: true
